// Copyright 2023 kilipan (@kilipan)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#ifdef RGBLIGHT_ENABLE
#define RGBLIGHT_DEFAULT_HUE 128
#define RGBLIGHT_DEFAULT_SAT 0
#define RGBLIGHT_DEFAULT_VAL 20
#define RGBLIGHT_LIMIT_VAL 20
#define RGBLIGHT_DEFAULT_SPD 20
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT
#define RGBLIGHT_SLEEP
#endif
